[app]
  #app名称
  name = "project-web"
  url = "http://localhost"
  port = ":8080"
  debug = false

[database]
  dirver = "mysql"

[mysql]
  dbname = "@tcp(127.0.0.1:3306)/superstar?charset=utf8"
  username = "root"
  password = "333"

[website]
  static_uri = "/static"
  site_title = "后台管理"
  copy_right = "<small>&copy;2019</small>"

[image]
  image_lib = "Imagick" # GD || Imagick
  image_path   = "../app_images/" #// 目录可读写
  image_url    = "image/" #// http://static.xxx.com/image/car_photo/150x150/19/sdddddd
  image_org    = 'org' #// 原图路径名
  image_tmp    = "tmp" #// 临时路径名
  image_types  = "jpg,jpeg,png,gif"
  water_mark   = ""
  array = ["1","2","3"]
  #// 汽车品牌LOGO
  image_categroy = "image_categroy"

[image_categroy]
    car_logo = "car_logo"
    img_logo = "img_logo"
[car_logo]
    #// 哈希路径
    paths = "/car_logo/org/"
    #// 支持的尺寸
    sizes = ["100x100","200x200"]
[img_logo]
   paths = "/car_logo/100*100/"
